# fly.toml app configuration file generated for sg-wiki on 2024-04-07T11:38:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sg-wiki'
primary_region = 'ewr'

[build]
  image = 'ghcr.io/requarks/wiki:2.5'

[env]
  DB_FILEPATH = '/data/db'
  DB_TYPE = 'sqlite'

[[mounts]]
  source = 'wiki_data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = "1GB"
  processes = [ "app" ]
  size = "shared-cpu-1x"
